[package]
name = "qip"
version = "0.6.3"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
description = "A library for efficient quantum computing simulations."
repository = "https://github.com/Renmusxd/RustQIP"
license = "MIT"
edition = "2018"

[lib]
name = "qip"

[dependencies]
num = "^0.2"
rayon = "^1.0"
bencher = "^0.1.5"
rand = "^0.6"

[[bench]]
name = "state_bench"
harness = false