[package]
name = "qip"
version = "0.2.1"
authors = ["sumnernh@gmail.com <sumnernh@gmail.com>"]
description = "A library for efficient quantum computing simulations."
license = "MIT"
edition = "2018"

[lib]
name = "qip"

[dependencies]
num = "^0.2.0"
rayon = "^1.0.3"
bencher = "^0.1.5"
rand = "^0.6"

[[bench]]
name = "state_bench"
harness = false